### ISSUE TITLE
Had to make my own journal dir after install

### ISSUE THREAD

**Issue by rjpcasalino** [bsima/jour#1]
`Traceback (most recent call last):
  File "/usr/local/bin/jour", line 46, in <module>
    raise NotADirectoryError("{0} does not exist.".format(journal_dir))
NotADirectoryError: /Users/Ryan/journal does not exist.`

Made one myself, but would be cool if install went ahead and did it on its own.

Also: found this on Lobsters! 

Small world! 

Hope you're doing well.

**Comment by rjpcasalino** [comment]
see https://github.com/bsima/jour/pull/2

**Comment by bsima** [comment]
oh hey ryan, thanks for addition! 

merged :ok_hand:
