### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by PeterBeard** [bsima/jour#3]
I noticed this code doesn't have a license associated with it. A lot of people won't contribute to a project unless it's clear what the license is. Also, without a license, nobody else is technically allowed to use, improve, or redistribute this code, so you should specify a license if that's not what you intended. You can take a look at http://choosealicense.com/ if you haven't thought about what license you'd like to use.

Anyway, thanks a lot for making this and (hopefully) making it free software.

**Comment by bsima** [comment]
Added the BSD license a few days ago but forgot to push... it's in master now as of commit 57c41c0. Thanks for the reminder :)
